version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    networks:
      - haila-network

  app1:
    build: .
    image: haila-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - haila-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 200M

  app2:
    build: .
    image: haila-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - haila-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 200M

  haproxy:
    image: haproxy:2.8
    ports:
      - "9999:9999"
    networks:
      - haila-network
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M

networks:
  haila-network:
    driver: overlay
